---
version: 1

destination: vagrant-vb

vagrant-vb:
    vagrantfile_location: /tmp

vagrant-kvm:
    box_url: https://vagrant-kvm-boxes.s3.amazonaws.com/trusty64_kvm.box

vagrant-docker:
    image: ubuntu:14.04    

trystack:
    auth_url: http://8.43.86.2:5000/v2.0

aws:
    region: us-east-1

docker:
    image: ubuntu:14.04

openstack:
    identity_v3:
        auth_url: http://127.0.0.1:5000
        auth_user: admin
        auth_pass: nomoresecret
        auth_tenant: admin
        auth_domain: default

hosts:
    monitor:
        ssh_host: 127.0.0.1
        ssh_port: 2222
        ssh_auth_type: password
        ssh_user: ubuntu
        ssh_pass: pass
    target:
        ssh_host: 127.0.0.1
        ssh_port: 2223
        ssh_auth_type: public-key
        ssh_user: ubuntu
        ssh_key_file: /tmp/id_rsa
