---
version: 1

destination: hosts

vagrant-vb:
    vagrantfile_location: /Volumes/120GB/vagrants/2-nodes
    monitor:
        setup: monitor-setup.sh
        install:
            type: bash-script
            file: monitor-installer.sh
    target:
        setup: target-setup.sh
        install:
            type: ansible-playbook
            file: target-installer.yaml

openstack:
    identity_v3:
        auth_url: http://127.0.0.1:5000
        auth_user: admin
        auth_pass: nomoresecret
        auth_tenant: admin
        auth_domain: default
    monitor:
        setup: monitor-setup.sh
        install:
            type: bash-script
            file: monitor-installer.sh
    target:
        setup: target-setup.sh
        install:
            type: ansible-playbook
            file: target-installer.yaml

hosts:
    monitor:
        ssh_host: 127.0.0.1
        ssh_port: 2222
        ssh_auth_type: password
        ssh_user: ubuntu
        ssh_pass: pass
        setup: monitor-setup.sh
        install:
            type: bash-script
            file: monitor-installer.sh
    target:
        ssh_host: 127.0.0.1
        ssh_port: 2223
        ssh_auth_type: public-key
        ssh_user: vagrant
        ssh_key_file: /Volumes/120GB/vagrants/2-nodes/.vagrant/machines/target/virtualbox/private_key
        setup: target-setup.sh
        install:
            type: ansible-playbook
            file: target-installer.yaml
